### ISSUE TITLE
Proposal: NewRequest in authenticate should return error instead of panic

### ISSUE THREAD

**Issue by pbabbicola** [AbiosGaming/go-sdk-v2#12]
[`authenticate`](https://github.com/AbiosGaming/go-sdk-v2/blob/master/abios_sdk.go#L122) should return an error instead of panicking if [`NewRequest`](https://github.com/AbiosGaming/go-sdk-v2/blob/master/abios_sdk.go#L127) fails.

Additionally, [`NewWithUrl`](https://github.com/AbiosGaming/go-sdk-v2/blob/a10a81e97eb782d2c787eeb98c88e5b790a83dc9/abios_sdk.go#L104) should either specify in the documentation that the url needs to be `/` terminated, or force it to be.

I can implement this if it is okayed.

**Comment by patstrom** [comment]
Ah yeah all of this is fair.

We assumed the `NewRequest` would never fail since it was added before the whole `NewWithUrl`. Then we added `NewWithUrl` in to use internally for our testing environment and didn't think much of it. That's why it's not really documented that well.

May I ask what you are using it for?

**Comment by pbabbicola** [comment]
Same reason! Unit testing. But I came across a strange error which I did not understand, which turned out to be because I used `NewWithURL` with directly the URL of the mocked server (`httptest.Server.URL`) which has no trailing slash :)

**Comment by pbabbicola** [comment]
Thanks so much for the fixes, you are great :)
